# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.20.5-standalone-strict/_definitions.json

apiVersion: extensions/v1beta1
kind: Jobs
metadata:
  name: jobs-demo
  namespace: demos
spec:
  selector:
    matchLabels:
      demo: jobs
  parallelism: 5
  completions: 15
  backoffLimit: 2
  template:
    metadata:
      labels:
        demo: jobs
    spec:
      containers:
        - name: sleep
          image: busybox
          command:
            [
              "sh",
              "-c",
              "sleep 5; if [ $((RANDOM % 4)) -eq 0 ]; then exit 1; fi",
            ]
      restartPolicy: Never
